[package]
name = "synology"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.2"
reqwest = "0.12.23"
tokio = { version = "1.47.1", features = ["fs", "macros", "net", "rt-multi-thread", "signal"] }
